name: Frontend CI-CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get Code
        uses: actions/checkout@v4

      - name: 2. Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Install Libraries
        run: npm install

      - name: 4. Build Project
        run: npm run build

      - name: 5. Run Greeting
        run: echo "Hello, this is Saleh CI-CD Pipeline"
